---
services: docker

env:
  - distro: ubuntu1604
  - ANSIBLE_VERSION: latest
  - ANSIBLE_VERSION: 2.3.2.0
  - ANSIBLE_VERSION: 2.2.3.0

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  # - ${PWD}/tests/test.sh
  - make travis
