---
# tasks file for bossjones.common

- name: Update apt keys
  command: apt-key update

- name: Update apt
  apt: update_cache=yes
  become: true

- name: Install base user packages.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ boss__common_base_packages }}"

- name: Disable ipv6.
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: boss__common_disable_ipv6 is defined

# - name: Ensure that configuration is supported
#   assert:
#     that: not boss__common_ntp_daemon or boss__common_ntp_daemon in [ 'ntpd', 'ntpdate', 'openntpd', 'systemd-timesyncd' ]

# - name: Install required packages
#   apt:
#     name: '{{ item }}'
#     state: '{{ "present" if (ansible_local|d() and ansible_local.ntp|d()) else "latest" }}'
#     install_recommends: False
#   with_items: [ 'tzdata' ]

# - name: Ensure that alternative daemons/programs are not installed
#   apt:
#     name: '{{ item }}'
#     state: 'absent'
#     purge: True
#   with_flattened:
#     - [ '{{ "ntpdate" if (boss__common_ntp_daemon != "ntpdate" and not boss__common_ntp_ignore_ntpdate|bool) else [] }}' ]
#     - [ '{{ "ntp" if (boss__common_ntp_daemon not in [ "ntpd", "openntpd"]) else [] }}' ]
#     - [ '{{ "openntpd" if (boss__common_ntp_daemon != "openntpd") else [] }}' ]

- name: Set timezone.
  copy:
    content: "{{boss__common_ntp_timezone}}"
    dest: /etc/timezone
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: yes
  notify:
    - update timezone

- name: Configure ntp.
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Start and enable ntp service.
  service:
    name: "{{boss__common_ntp_daemon}}"
    state: started
    enabled: true

